import { Injectable, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Customer } from '../../entities/customer.entity';
import { Contact } from '../../entities/contact.entity';
import { User } from '../../entities/user.entity';
import { Role } from '../../entities/role.entity';
import { Technician } from '../../entities/technician.entity';
import { Mailbox } from '../../entities/mailbox.entity';
import { CryptoService } from '../../crypto/crypto.service';
import { RoleName, TechnicianStatus, TechnicianLevel } from '../../common/enums';

export interface ZammadOrg {
  id: number | string;
  name: string;
}
export interface ZammadUser {
  id: number | string;
  email: string;
  firstname: string;
  lastname: string;
  role: string; // Admin | Agent | Customer
  active: boolean;
  legacy_argon2_hash: string;
}
export interface ZammadEmailChannel {
  area: string;
  email: string;
  adapter: string;
  host: string;
  port: number;
  user: string;
  ssl: boolean;
}
export interface ZammadMeta {
  organizations: ZammadOrg[];
  users: ZammadUser[];
  email_channels: ZammadEmailChannel[];
}
export interface ImportResult {
  customersCreated: number;
  usersCreated: number;
  techniciansCreated: number;
  contactsCreated: number;
  mailboxesCreated: number;
}

@Injectable()
export class ZammadMetaImportService {
  private readonly logger = new Logger(ZammadMetaImportService.name);

  // Emails generated by mail systems / third-party notifications that appear as
  // Zammad "Customer" senders but are NOT real people. We never create a Contact
  // (portal account) for these.
  private static readonly SYSTEM_EMAIL_RE = new RegExp(
    [
      '@zammad\\.org',
      '@microsoft\\.com',
      '@accountprotection\\.microsoft',
      '@communication\\.microsoft',
      '@trello\\.com',
      '@evernote\\.com',
      '@accounts\\.evernote',
      '@notifications\\.evernote',
      '@messages\\.evernote',
      '@mail\\.evernote',
      '@accounts\\.google',
      'no-reply',      // no-reply@..., noreply@
      'do-not-reply',  // do-not-reply@...
      'invitation',    // invitation-do-not-reply@...
      '^cpanel@',
    ].join('|'),
    'i',
  );

  private static isSystemEmail(email: string): boolean {
    return this.SYSTEM_EMAIL_RE.test(email);
  }

  // Free-mail / personal-mailbox domains. A contact on these has NO identifiable
  // company, so we group them in a single generic Customer ("Clientes
  // particulares") instead of creating a fake "Gmail"/"Hotmail" company.
  private static readonly PERSONAL_EMAIL_RE = /(^|[.@])(gmail|hotmail|yahoo|outlook|live|icloud|msn|aol|protonmail|proton\.me|ymail|zoho|gmx|mail\.com|tutanota)\.(com|net|org|ar|es)$/i;

  // Name for the generic Customer holding contacts without an identifiable company.
  private static readonly PRIVATE_CUSTOMER_NAME = 'Clientes particulares';

  constructor(
    @InjectRepository(Customer) private readonly customers: Repository<Customer>,
    @InjectRepository(Contact) private readonly contacts: Repository<Contact>,
    @InjectRepository(User) private readonly users: Repository<User>,
    @InjectRepository(Role) private readonly roles: Repository<Role>,
    @InjectRepository(Technician) private readonly technicians: Repository<Technician>,
    @InjectRepository(Mailbox) private readonly mailboxes: Repository<Mailbox>,
    private readonly crypto: CryptoService,
  ) {}

  async import(meta: ZammadMeta): Promise<ImportResult> {
    const result: ImportResult = {
      customersCreated: 0,
      usersCreated: 0,
      techniciansCreated: 0,
      contactsCreated: 0,
      mailboxesCreated: 0,
    };

    // 1) Organizations -> Customer (independent, before users/contacts).
    const customerByName = new Map<string, Customer>();
    for (const org of meta.organizations || []) {
      const name = (org.name || '').trim();
      if (!name) continue;
      let customer = await this.customers.findOne({ where: { name } });
      if (!customer) {
        customer = await this.customers.save(this.customers.create({ name, active: true }));
        result.customersCreated++;
      }
      customerByName.set(name, customer);
    }

    // Resolve the fallback Customer for a contact that does not match an org by
    // name: infer it from the email domain (corporate domains create one Customer
    // per domain; personal domains all go to the generic "Clientes particulares").
    const customerByDomain = new Map<string, Customer>();
    let privateCustomer: Customer | null = null;
    const resolveFallbackCustomer = async (email: string): Promise<Customer> => {
      const domain = (email.split('@')[1] || '').toLowerCase();
      if (ZammadMetaImportService.isPersonalEmail(domain)) {
        if (!privateCustomer) {
          privateCustomer = await this.ensureCustomerByName(
            ZammadMetaImportService.PRIVATE_CUSTOMER_NAME,
            result,
          );
        }
        return privateCustomer;
      }
      const cached = customerByDomain.get(domain);
      if (cached) return cached;
      const display = ZammadMetaImportService.companyNameFromDomain(domain);
      const customer = await this.ensureCustomerByName(display, result);
      customerByDomain.set(domain, customer);
      return customer;
    };

    // 2) Users: Agents/Admins -> SolidOps User (mapped role + Technician profile),
    //    Customers -> Contact (portal_enabled), matched to the org customer by
    //    lastname/name when possible, else inferred by email domain.
    for (const u of meta.users || []) {
      const email = (u.email || '').toLowerCase().trim();
      if (!email) continue;

      if (u.role === 'Customer') {
        // Never create portal contacts for system/notification senders.
        if (ZammadMetaImportService.isSystemEmail(email)) {
          this.logger.warn(`Se omite Customer de sistema: ${email}`);
          continue;
        }
        await this.migrateCustomerUser(u, customerByName, resolveFallbackCustomer, result);
      } else {
        await this.migrateStaffUser(u, result);
      }
    }

    // 3) Email channels -> Mailbox (encrypted creds, shadow_mode default true? no —
    //    leave as the platform default; the operator enables shadow as needed).
    for (const ch of meta.email_channels || []) {
      const email = (ch.email || '').toLowerCase().trim();
      if (!email) continue;
      const hasInbound = ch.host && ch.user;
      if (!hasInbound) continue;
      const exists = await this.mailboxes.findOne({ where: { email } });
      if (exists) continue;
      // Password not present in this export (Zammad stores secrets separately);
      // the operator must fill IMAP/SMTP credentials from the Zammad console.
      // We create the mailbox with empty password so it can be completed in the UI.
      await this.mailboxes.save(
        this.mailboxes.create({
          email,
          imapHost: ch.host,
          imapPort: ch.port || 993,
          imapUser: ch.user,
          imapPassword: this.crypto.encrypt('__pending__'),
          imapSsl: ch.ssl,
          smtpHost: null,
          smtpPort: null,
          smtpUser: null,
          smtpPassword: null,
          smtpSsl: true,
          keepOnServer: true,
          active: false, // inactive until operator fills real credentials
          shadowMode: false,
        }),
      );
      result.mailboxesCreated++;
    }

    this.logger.log(
      `Import Zammad meta: ${result.customersCreated} clientes, ${result.usersCreated} usuarios, ` +
        `${result.techniciansCreated} técnicos, ${result.contactsCreated} contactos, ${result.mailboxesCreated} casillas.`,
    );
    return result;
  }

  private async migrateStaffUser(u: ZammadUser, result: ImportResult) {
    const email = u.email.toLowerCase().trim();
    const existing = await this.users.findOne({ where: { email } });
    if (existing) {
      // If the account already exists but the export carries a real Argon2id
      // hash, arm lazy migration: empty the bcrypt hash so the FIRST login
      // verifies against the imported Zammad password and then re-hashes to
      // bcrypt. This lets an admin sign in with the exact Zammad password.
      if (u.legacy_argon2_hash && existing.legacyArgon2Hash !== u.legacy_argon2_hash) {
        existing.legacyArgon2Hash = u.legacy_argon2_hash;
        existing.passwordHash = null;
        await this.users.save(existing);
        this.logger.log(`Usuario existente armado para lazy migration: ${email}`);
      }
      return;
    }

    const roleName = u.role === 'Admin' ? RoleName.ADMINISTRADOR : RoleName.TECNICO;
    const role = await this.roles.findOne({ where: { name: roleName } });
    if (!role) {
      this.logger.warn(`Rol ${roleName} no encontrado; se omite ${email}`);
      return;
    }
    const displayName = [u.firstname, u.lastname].filter(Boolean).join(' ').trim() || email;

    const user = await this.users.save(
      this.users.create({
        name: displayName,
        email,
        // No bcrypt hash for migrated accounts: leave passwordHash null so the
        // FIRST login verifies against legacy_argon2_hash (Argon2id) and only
        // then generates a bcrypt hash. Setting '' would still be truthy-checked
        // incorrectly if the column is read as a string; null is unambiguous.
        passwordHash: null,
        legacyArgon2Hash: u.legacy_argon2_hash || null,
        roleId: role.id,
        active: u.active !== false,
      }),
    );
    result.usersCreated++;

    // Every Agent/Admin gets a Technician profile (specialties/level left blank).
    await this.technicians.save(
      this.technicians.create({
        userId: user.id,
        specialties: [],
        level: TechnicianLevel.MID,
        status: TechnicianStatus.DISPONIBLE,
        schedule: {},
        avatarUrl: null,
        notes: null,
      }),
    );
    result.techniciansCreated++;
  }

  private async migrateCustomerUser(
    u: ZammadUser,
    customerByName: Map<string, Customer>,
    resolveFallback: (email: string) => Promise<Customer>,
    result: ImportResult,
  ) {
    const email = u.email.toLowerCase().trim();
    const existing = await this.contacts.findOne({ where: { email } });
    if (existing) return;

    const displayName = [u.firstname, u.lastname].filter(Boolean).join(' ').trim() || email.split('@')[0];
    // Match the org by lastname (commonly the org name) or by full name.
    let customer = customerByName.get(u.lastname || '') ?? customerByName.get(displayName);
    // No direct org match -> infer a Customer from the email domain.
    if (!customer) customer = await resolveFallback(email);

    await this.contacts.save(
      this.contacts.create({
        customerId: customer.id,
        name: displayName,
        email,
        phone: null,
        whatsapp: null,
        preferredChannel: 'email' as never,
        portalEnabled: true,
        portalPasswordHash: null,
        legacyArgon2Hash: u.legacy_argon2_hash || null,
      }),
    );
    result.contactsCreated++;
  }

  private static isPersonalEmail(domain: string): boolean {
    return this.PERSONAL_EMAIL_RE.test(domain);
  }

  // "mail.melacrom.com.ar" -> "Melacrom"; "industriassparks.com.ar" ->
  // "Industriassparks". Removes sub-domains and TLDs, title-cases the label.
  private static companyNameFromDomain(domain: string): string {
    const parts = domain.split('.');
    const labels = parts.filter((p) => p && !['com', 'net', 'org', 'ar', 'es', 'mx', 'co', 'cl', 'uy', 'www', 'mail'].includes(p));
    let label = labels[0] || parts[0] || domain;
    label = label.replace(/[_-]+/g, ' ').trim();
    return label
      .split(' ')
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join(' ');
  }

  private async ensureCustomerByName(name: string, result: ImportResult): Promise<Customer> {
    let customer = await this.customers.findOne({ where: { name } });
    if (!customer) {
      customer = await this.customers.save(this.customers.create({ name, active: true }));
      result.customersCreated++;
    }
    return customer;
  }
}
